name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        dotnet: ["6.0", "7.0", "8.0", "9.0"]

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Install dependencies
      run: dotnet restore Omise.sln
    - name: Test
      run: make test TargetDotNet=${{ matrix.dotnet }}
